### ISSUE TITLE
CDISC-GLOSS to CDISC Glossary

### ISSUE THREAD

**Issue by mike-hamidi** [HL7/Vulcan-schedule-ig#14]
URL: https://build.fhir.org/ig/HL7/Vulcan-schedule-ig/index.html#what-is-the-schedule-of-activities
Comment: Can we spell "GLOSS" as "Glossary", as many non-CDISC consumers may not understand such abbreviations. It is synonymous with the "CDISC-GLOSS Definition" in NCIm. There is also a corresponding NCIt Definition: "A planned list of clinical trial activities to include interventions, assessments, and study administrative activities." https://ncimetathesaurus.nci.nih.gov/ncimbrowser/ConceptReport.jsp?dictionary=NCI%20Metathesaurus&code=CL521320

**Comment by glow-mdsol** [comment]
Maybe linking to external terminologies such as BRIDG/NCI Metathesaurus

**Comment by glow-mdsol** [comment]
https://www.markdownguide.org/extended-syntax/#footnotes for footnote

**Comment by mike-hamidi** [comment]
Confirmed change

**Comment by glow-mdsol** [comment]
Closing
