### ISSUE TITLE
Example of Benefits

### ISSUE THREAD

**Issue by mike-hamidi** [HL7/Vulcan-schedule-ig#15]
**URL**: https://build.fhir.org/ig/HL7/Vulcan-schedule-ig/index.html#vulcan-soa-implementation-guide-ig
**Comment**: In addition to site feasibility (not patient), there's the critical impact of study site efficiency using a machine-readable, FHIR enabled, SoA. Some items may not fall entirely under SoA but can help enable them (e.g., hospital administrative factors). As a side note, the eligibility feasibility is still undergoing discussion via EvidenceVariable and future Vulcan projects. Side note, the audit/inspection is a general requirement that must be followed. Not sure how the SoA would change this, even if its represented via FHIR.

**Comment by glow-mdsol** [comment]
Add more benefits to set, expand out audit/inspection considerations

**Comment by AndyR1217** [comment]
Values of FHIR specified SoAs:  
... for sponsors
..,, for sites
... for central laboratories...
... for others, specify...

**Comment by glow-mdsol** [comment]
Jeff A to contribute as well

**Comment by dnewingh** [comment]
Brainstorming some additional positive outcomes:
- Protocol adherence – streamlined deployment of protocol updates
- Portfolio management – reporting consistency across sites
- Site operational efficiency – task automation (e.g. order entry, reminders, etc) based on SoA

**Comment by mike-hamidi** [comment]
Confirming updates

**Comment by glow-mdsol** [comment]
Closing for the moment
