### ISSUE TITLE
Cleanup Placeholder Text

### ISSUE THREAD

**Issue by mike-hamidi** [HL7/Vulcan-schedule-ig#18]
**URL**: https://build.fhir.org/ig/HL7/Vulcan-schedule-ig/basic-structure.html   (under Implementing an SoA using FHIR Resources)
**Comment**: There's a placeholder text above the code snippet that states, "It is also possible to define the interval between these actions as illustrated here (using FSH syntax - INSERT LINK TO FSH LINK):"

Check all other pages for similar placeholders.

**Comment by glow-mdsol** [comment]
Part of a broader work to incorporate more examples into the IG based on work done prior (phuse-gh).  Ensure that the context and content is sufficient to make sense

**Comment by mike-hamidi** [comment]
Confirmed. Thanks
