### ISSUE TITLE
FHIR & ODM

### ISSUE THREAD

**Issue by mike-hamidi** [HL7/Vulcan-schedule-ig#19]
**URLs**:  https://build.fhir.org/ig/HL7/Vulcan-schedule-ig/basic-structure.html; https://build.fhir.org/ig/HL7/Vulcan-schedule-ig/cdisc-odm.html
**Comment**: I wonder if a separate FHIR-to-ODM mapping is required due to its technical and semantic nature. Therefore, maybe we keep what's already included as a high-level concept but mention additional work is required to develop canonical mappings.

P.S. 
We can create a separate PHUSE or Vulcan project - maybe even bring it back to the CDISC ODM team.

**Comment by glow-mdsol** [comment]
Don't totally think they are totally aligned - ODM is more of a structual model; interpretation may be objective.   There are links (on the content level) added by Jozef

**Comment by glow-mdsol** [comment]
We've refactored the role of ODM in the IG, can this be closed?

**Comment by mike-hamidi** [comment]
Yes. It seems to have solved the original comment mentioned here.
