### ISSUE TITLE
Explicitness of FHIR vs SoA Terminology

### ISSUE THREAD

**Issue by mike-hamidi** [HL7/Vulcan-schedule-ig#20]
**URL**: https://build.fhir.org/ig/HL7/Vulcan-schedule-ig/visit-windows.html
**Comment**: I think it's important to distinguish between terminologies clearly (e.g., when we say visit vs. actual FHIR resources such as Encounter). In cases where an FHIR resource, data type, etc. are referenced, then link to them directly. This will ensure we can differentiate between them. The intent is to bridge the understanding across a diverse set of consumers.

**Comment by glow-mdsol** [comment]
Change Bold/Italic to links?

**Comment by mike-hamidi** [comment]
Confirmed. I would recommend the entire team do a review.
