### ISSUE TITLE
Section Numbering

### ISSUE THREAD

**Issue by mike-hamidi** [HL7/Vulcan-schedule-ig#23]
**URL**: https://build.fhir.org/ig/HL7/Vulcan-schedule-ig/ip-administration.html#scenarios
**Comment**: All the sections are identified as "4" which is not correct. In addition, it would be easier to follow if the specific scenarios have their own unique sub-section identifier (e.g., 4.1.1, 4.1.2, etc.). In FHIR IGs, there are relative links that can be used.

**Comment by mike-hamidi** [comment]
Is this still correct?
https://build.fhir.org/ig/HL7/Vulcan-schedule-ig/ip-administration.html#investigational-product-administration has Section 4, and so does https://build.fhir.org/ig/HL7/Vulcan-schedule-ig/ip-administration.html#scenarios

**Comment by glow-mdsol** [comment]
Apologies, updated

**Comment by glow-mdsol** [comment]
fixed
