### ISSUE TITLE
Medication Last Example

### ISSUE THREAD

**Issue by mike-hamidi** [HL7/Vulcan-schedule-ig#25]
**URL**: https://build.fhir.org/ig/HL7/Vulcan-schedule-ig/ip-administration.html#ip-administration-at-home
**Comment**: What do the non-solid circles entail? The current wording states, "In this case the IP is initially taken during the clinic visit generating a MedicationAdminstration.status record of ‘completed’ (solid circle) and four ‘in progress’ records reflecting the protocol expectation."

**Comment by mike-hamidi** [comment]
I don't think this has been resolved yet. 
Green Circle=assumes the start of something
Red Circle=assumes the end of something
Gray Circle=assumes something
White Circle=assumes something

**Comment by AndyR1217** [comment]
Figure legend added to page.
