### ISSUE TITLE
Resource Profile: ResearchStudySoa

### ISSUE THREAD

**Issue by mike-hamidi** [HL7/Vulcan-schedule-ig#31]
**URL**: https://build.fhir.org/ig/HL7/Vulcan-schedule-ig/StructureDefinition-ResearchStudySoa.html
**Comment**: It looks like three elements are required via profiling. Since we're talking about the SoA, other attributes should be included (e.g., you can't use the SoA IG without PlanDefinition from a ResearchStudy). Otherwise, should I assume that the separate PlanDefinition profiles infer this?

**Comment by glow-mdsol** [comment]
One for @jduteau I think

**Comment by jduteau** [comment]
I have added all of the elements that we use in our example to be MustSupport.
