### ISSUE TITLE
Unscheduled Activities

### ISSUE THREAD

**Issue by glow-mdsol** [HL7/Vulcan-schedule-ig#34]
Thread:

[16:29] Hamidi, Mike
I think what your looking for is additional guidance to an actor(s) at the organization to do A or B when something does not follow the PlanDefinition via Flag. However, we are moving into prescriptive territory that requires proper execution via actual care.

[16:46] Hamidi, Mike
For example, PlanDefinition states that Mike should get his pulse taken on Oct. 26th @ 10 AM (Visit 1), but his appointment was updated due to his inability to get to the site. So, his new appointment is scheduled for Oct. 27th @12, which still falls within the original PlanDefinition Visit 1 (i.e., within the 2-3 day window). Another scenario is when that falls outside of the window i.e. after Visit 1 and before Visit 2 or into Visit 2. So, do we 1) have multiple PlanDefinition for all potential occurrences, 2) an attribute to detail this occurrence, or 3) another resource to instruct sites (e.g., Flag)

[16:47] Hamidi, Mike
Andy Richardson Agreed. Otherwise, we can end up with hundreds of PlanDefinitions

[16:58] Hamidi, Mike
The other issue is that we have not expanded the scope to go beyond the SoA. Yes, there's a lot more information in the overall protocol. Excluding the SoA footers.

**Comment by glow-mdsol** [comment]
Decision that needs to be made - include or don't include the Unscheduled activity use case

**Comment by AndyR1217** [comment]
For this IG my view is that any protocol SoA 'Unscheduled Visit' **activities** have to be recognised and represented in the same way as any other visit.   Navigation to/from, when/why, if.. etc. should be left for consideration for inclusion in a future release

**Comment by glow-mdsol** [comment]
How about unscheduled activities (ie not visits)?

**Comment by rebeccabaker1** [comment]
Hi,It may add value.When is the deadline?We could add the query to find them…?Thanks.Rebecca On Oct 30, 2022, at 5:35 PM, Geoff Low ***@***.***> wrote:﻿
How about unscheduled activities (ie not visits)?

**Comment by glow-mdsol** [comment]
Remove content relating to unscheduled activities, reference to say it was an important use case but wasn't ready to go

**Comment by glow-mdsol** [comment]
moved the current state to a backlog branch and removed the file.  Good to close now
