### ISSUE TITLE
Section 2.2 - Image Link Broken

### ISSUE THREAD

**Issue by mike-hamidi** [HL7/Vulcan-schedule-ig#38]
URL: https://build.fhir.org/ig/HL7/Vulcan-schedule-ig/basic-structure.html#implementing-a-soa-using-fhir-resources
Comment: The "​Schedule of Activities Basic Structure" image is broken

**Comment by glow-mdsol** [comment]
Oh Rats

**Comment by glow-mdsol** [comment]
fixed
